# SPDX-License-Identifier: GPL-2.0-only

# auto-detect subdirs
ifneq ($(CONFIG_BUILD_VENDORSI), true)
ifneq ($(CONFIG_ARCH_QTI_VM), y)
include $(srctree)/techpack/cvp/config/waipioeva.conf
LINUXINCLUDE    += -include $(srctree)/techpack/cvp/config/waipioevaconf.h
endif

LINUXINCLUDE    += -I$(srctree)/techpack/cvp/include \
                   -I$(srctree)/techpack/cvp/include/uapi \
		   -I$(srctree)/techpack/cvp/include/uapi/eva
endif

obj-y +=msm/
