RMNET_CORE_INC_DIR = $(srctree)/techpack/datarmnet/core

ifeq ($(CONFIG_QGKI),y)
obj-y += rmnet_wlan.o
else
obj-m += rmnet_wlan.o
endif
ccflags-y := -I$(RMNET_CORE_INC_DIR) \
	$(call cc-option,-Wno-misleading-indentation)
rmnet_wlan-y := \
	rmnet_wlan_main.o \
	rmnet_wlan_genl.o \
	rmnet_wlan_stats.o \
	rmnet_wlan_fragment.o \
	rmnet_wlan_connection.o
