RMNET_CORE_INC_DIR = $(srctree)/techpack/datarmnet/core

ifeq ($(CONFIG_QGKI),y)
obj-y += rmnet_shs.o
else
obj-m += rmnet_shs.o
endif
#Need core headers
ccflags-y := -I$(RMNET_CORE_INC_DIR) \
             $(call cc-option,-Wno-misleading-indentation)
rmnet_shs-y :=  rmnet_shs_config.o \
		rmnet_shs_ll.o \
		rmnet_shs_main.o \
		rmnet_shs_common.o \
		rmnet_shs_wq.o \
		rmnet_shs_freq.o \
		rmnet_shs_wq_mem.o \
		rmnet_shs_wq_genl.o \
		rmnet_shs_modules.o
