# SPDX-License-Identifier: GPL-2.0-only

MSM_EXT_DISPLAY_ROOT := $(srctree)/techpack/mm/msm_ext_display

ifeq ($(CONFIG_QGKI),y)
include $(MSM_EXT_DISPLAY_ROOT)/../config/kalamammdrivers.conf
else
include $(MSM_EXT_DISPLAY_ROOT)/../config/gki_kalamammdrivers.conf
endif
LINUXINCLUDE += -include $(MSM_EXT_DISPLAY_ROOT)/../config/kalamammdriversconf.h

obj-$(CONFIG_MSM_EXT_DISPLAY) += msm_ext_display.o

msm_ext_display-y := src/msm_ext_display.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
