# SPDX-License-Identifier: GPL-2.0-only

SYNC_FENCE_ROOT := $(srctree)/techpack/mm/sync_fence

LINUXINCLUDE    += -I$(SYNC_FENCE_ROOT)/include/
ifeq ($(CONFIG_QGKI),y)
include $(SYNC_FENCE_ROOT)/../config/kalamammdrivers.conf
else
include $(SYNC_FENCE_ROOT)/../config/gki_kalamammdrivers.conf
endif
LINUXINCLUDE += -include $(SYNC_FENCE_ROOT)/../config/kalamammdriversconf.h

obj-$(CONFIG_QCOM_SPEC_SYNC) += sync_fence.o

sync_fence-y := src/qcom_sync_file.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
