AUDIO_ROOT := $(srctree)/techpack/audio

ifeq ($(CONFIG_ARCH_KONA), y)
include $(AUDIO_ROOT)/config/konaauto.conf
LINUXINCLUDE += -include $(AUDIO_ROOT)/config/konaautoconf.h
endif

LINUXINCLUDE += \
		-I$(AUDIO_ROOT)/include/uapi \
		-I$(AUDIO_ROOT)/include/uapi/audio \
		-I$(AUDIO_ROOT)/include/asoc \
		-I$(AUDIO_ROOT)/include
USERINCLUDE += -I$(AUDIO_ROOT)/include/uapi/audio

obj-y += soc/
obj-y += dsp/
obj-y += ipc/
obj-y += asoc/
